"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const user_1 = require("../controller/user");
const isAdmin_1 = __importDefault(require("../middleware/isAdmin"));
const updateUserPermission_1 = __importDefault(require("../middleware/updateUserPermission"));
const HandledRouter_1 = __importDefault(require("../utils/HandledRouter"));
const multer_1 = __importDefault(require("multer"));
HandledRouter_1.default.get("/", isAdmin_1.default, user_1.getAllUsers);
HandledRouter_1.default.get("/:id", updateUserPermission_1.default, user_1.getUserById);
HandledRouter_1.default.get("/:id/company", user_1.getCompanies);
HandledRouter_1.default.post("/:id/company", updateUserPermission_1.default, user_1.addCompany);
HandledRouter_1.default.patch("/:id/role", isAdmin_1.default, user_1.changeUserRole);
HandledRouter_1.default.patch("/:id/email", updateUserPermission_1.default, user_1.updateUser);
HandledRouter_1.default.put("/:id", updateUserPermission_1.default, user_1.updateUser);
HandledRouter_1.default.put("/:id/set-profile-picture", updateUserPermission_1.default, (0, multer_1.default)().single("image"), user_1.updateProfilePicture);
HandledRouter_1.default.put("/:id/set-cover-picture", updateUserPermission_1.default, (0, multer_1.default)().single("image"), user_1.updateCoverPicture);
HandledRouter_1.default.delete("/:id", isAdmin_1.default, user_1.deleteUser);
exports.default = HandledRouter_1.default.getRouter();
