export enum Error
{
    INVALID_TOKEN = "INVALID_TOKEN",
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
    USER_NOT_FOUND = "USER_NOT_FOUND",
    USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS",
    EMAIL_NOT_CONFIRMED = "EMAIL_NOT_CONFIRMED",
    EMAIL_ALREADY_CONFIRMED = "EMAIL_ALREADY_CONFIRMED",
    UNAUTHORIZED = "UNAUTHORIZED",
    INVALID_IMAGE_TYPE = "INVALID_IMAGE_TYPE",
    INVALID_IMAGE_SIZE = "INVALID_IMAGE_SIZE",
}