export enum Success
{
    ACCOUNT_DELETED = "ACCOUNT_DELETED",
    EMAIL_CONFIRMED = "EMAIL_CONFIRMED",
    EMAIL_SENT = "EMAIL_SENT",
    PASSWORD_CHANGED = "PASSWORD_CHANGED",
    PROFILE_UPDATED = "PROFILE_UPDATED",
}